### ISSUE TITLE
Create the action.yml file

### ISSUE THREAD

**Issue by thepetk** [thepetk/projectman#3]
/type task

## Which area/kind this task is related to?

/label ci

## Issue Description

A required step for every github action is to create an `action.yml`. More information about the process can be found here: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code

A template that we can follow could be:

```yaml
# action.yml
name: 'projectman'
description: 'Manages github projects'
runs:
  using: 'docker'
  image: 'Dockerfile'
```
